# Generated by Django 3.2.25 on 2024-05-05 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the profile was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the profile was last updated.', verbose_name='Updated at')),
                ('name', models.CharField(blank=True, help_text='The name of the user for this profile.', max_length=255, verbose_name='Name')),
                ('content', models.TextField(blank=True, help_text="Additional content or description for the user's profile.", verbose_name='Content')),
                ('image', models.ImageField(default='../default_profile_pic_ciw1he.jpg', help_text='The profile image for the user.', upload_to='images/', verbose_name='Profile Image')),
                ('owner', models.OneToOneField(help_text='The user that this profile belongs.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
